@accessToken = eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZXMiOlsiQURNSU4iXSwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjQyMDBcLyIsInZlcmlmaWVkIjp0cnVlLCJleHAiOjE3NTExOTA5NzksInR5cGUiOiJBQ0NFU1MiLCJpYXQiOjE3MTk2NTQ5NzksImp0aSI6ImI1ZDNlZDUyZTg5YTQ1YmRiMTFhZjY2NjMzNzE5YzRhIn0.Erd8N9HSU7KfyOhQa8NwVILNh4r2YvD3v_DjoUOwLXMpA_Lhri3IDeE8fJ8-LY-q0IpOgP6GiuMMRqPj7LfNFTRoWcFGJ9z-EDE0lh89x6FPMGNDuumWS54U64Rp26mVq2IQbkc1Q6efOD8vNf0sP20ik_YWQ88t3_70QK8GpQYUDbJQ-dZBlUX0pbG9RRJy8FmE4oBbziXdHOGd2rO-I6PlXK5BqAMX31iCKtDaUAoMKAtMWjDNxoQEwvl0NXtktcPvZDjXxCT7awSZUCZ01825FXAW2oohXQAflH6tXkoYCk9pkrem4zX3irdOtW2vHhXOpFQM9vytBk0OePvs2w
@refreshToken = eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjQyMDBcLyIsImV4cCI6MTcxOTcyOTI5NCwidHlwZSI6IlJFRlJFU0giLCJpYXQiOjE3MTk2NDI4OTQsImp0aSI6ImY5ZjhhMzg1MTRlNDQxMzNhYWE3YWU5MTM1Y2I3YTJjIn0.SGhCAO0fbQjHRhyFMGGc-Ko6Jeb-m_nYBM-Wr7cPZIPV8hEdnMilXizif0NEFIITRay4i0kMQMZ-0A0qFWO6n6XGcMwoStClyvd-W9evr4ki13UpoY32DLOkkwSCZvVyhFp1qruODIZbtYfVGMi2s8V9TRKwUasfktdwF__CAfYX3Ih3Zx33NLaKKSgLzIasBXNyPXl2v-cwlzmEPen7l66tv6TRWDmTyS_pNrrKL8dW9tFcxfB3-dI0ew3qZIYGbmOF0SYbv0hgwPwyV3oEOmCiuXEBtwb3bsthP9JXhJLkyDRAKBlxul3QeC4y-6q5KPxLJwcf7ImAjLO70ehbKg


#### Login
POST http://localhost:820/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

#### Sign Up
POST http://localhost:820/v1/auth/sign-up
Content-Type: application/json

{
  "username": "admin_http",
  "password": "admin_http",
  "role": "ADMIN"
}

#### Refresh Token
POST http://localhost:820/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

#### Get Users
GET http://localhost:820/v1/users
Authorization: Bearer {{accessToken}}

#### Get Private
GET http://localhost:820/v1/private
Authorization: Bearer {{accessToken}}
