
@accessToken = eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IlNVUEVSX0FETUlOIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjQyMDBcL3dlYiIsImV4cCI6MTcxOTc1NDM2MywiaWF0IjoxNzE5NzUwNzYzLCJqdGkiOiI2NDM5ZTA5OGRhZWI0NGNhOTMxOTliOTA4OWMwODBkNCIsImF1dGhvcml0aWVzIjpbIkFETUlOOkRFTEVURSIsIkFETUlOOlJFQUQiLCJBRE1JTjpVUERBVEUiLCJBRE1JTjpXUklURSJdfQ.g72FOyQaWOgyR2O4zR6bXsRijHLJWGOzIvmIc7tIjUfUJg3lqi4lLf-UcpvYsKSgsapfkcqGwBYwNXD8XbXigub0asOHEiwKmwHDlWoMhibRof10mNPJvJxyyK1nBAVb_A15eeoVZ31xLofqFQ-g9SXhD-SZLkGQnVYWesIjAG-u3pgcuE1KuTejuQlkC1WRUK8ztgUW7wfR3mTkyyp0Q77kANShEU7K8vfFtMrmtXbGFE_TwzYSek-iaL8vEH-ew7AMq_lAbhf88fnre-LCd0phnefdgChUvptiHZpNZDw2hAnV5Tt1sAwlMyvhjan2ej_FbgcjXzMbyhxyINcMNw
@refreshToken = eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjQyMDBcLyIsImV4cCI6MTcxOTcyOTI5NCwidHlwZSI6IlJFRlJFU0giLCJpYXQiOjE3MTk2NDI4OTQsImp0aSI6ImY5ZjhhMzg1MTRlNDQxMzNhYWE3YWU5MTM1Y2I3YTJjIn0.SGhCAO0fbQjHRhyFMGGc-Ko6Jeb-m_nYBM-Wr7cPZIPV8hEdnMilXizif0NEFIITRay4i0kMQMZ-0A0qFWO6n6XGcMwoStClyvd-W9evr4ki13UpoY32DLOkkwSCZvVyhFp1qruODIZbtYfVGMi2s8V9TRKwUasfktdwF__CAfYX3Ih3Zx33NLaKKSgLzIasBXNyPXl2v-cwlzmEPen7l66tv6TRWDmTyS_pNrrKL8dW9tFcxfB3-dI0ew3qZIYGbmOF0SYbv0hgwPwyV3oEOmCiuXEBtwb3bsthP9JXhJLkyDRAKBlxul3QeC4y-6q5KPxLJwcf7ImAjLO70ehbKg


#### Login
POST http://localhost:820/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

#### Sign Up
POST http://localhost:820/v1/auth/sign-up
Content-Type: application/json

{
  "username": "admin_http",
  "password": "admin_http",
  "role": "ADMIN"
}

#### Refresh Token
POST http://localhost:820/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

#### Get Users
GET http://localhost:820/v1/users
Authorization: Bearer {{accessToken}}

#### Get Managers
GET http://localhost:820/v1/managers
Authorization: Bearer {{accessToken}}

#### Get Products
GET http://localhost:820/v1/products
Authorization: Bearer {{accessToken}}