version: '3'
services:
  server:
    build: .
    image: shop-server:latest
    container_name: shop_server
    ports:
      - "910:8080"
    networks:
      - server-net
    depends_on:
      - mysql
      - redis

  mysql:
    image: biarms/mysql:5.7
    container_name: shop_mysqldb
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - server-net

  redis:
    image: redis
    container_name: shop_redis
    ports:
      - "6379:6379"
    networks:
      - server-net

volumes:
  mysql-data:
networks:
  server-net: