spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&characterSetResults=utf8mb4
    username: dev
    password: 1234
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 Minute
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: natsukashiiz.dev@gmail.com
    password: zavn qpoh qpot ocmq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
shop:
  jwt:
    pvKey: classpath:app.key
    pubKey: classpath:app.pub
  google:
    clientId: 213921102049-buchqc6diom118vnsidm9fito3cr51dd.apps.googleusercontent.com
  payment:
    omise:
      pubKey: pkey_test_5un4a0mz82obwpz257q
      secretKey: skey_test_5un49ncyly5rx5dpjwi
  web:
    url:
      base: http://localhost:4200/web
      verification: http://localhost:4200/web/verification?code={CODE}
      resetPassword: http://localhost:4200/web/reset-password?email={EMAIL}&code={CODE}
      paymentReturn: http://localhost:4200/web/orders/detail/

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.natsukashiiz.shop: DEBUG
