spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_db?useSSL=false&serverTimezone=UTC
    username: root
    password: my-secret-pw
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: localhost
    port: 6379
shop:
  jwt:
    pvKey: classpath:app.key
    pubKey: classpath:app.pub
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.natsukashiiz.shop: DEBUG