server:
  port: 920
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://212.80.213.8:3306/shop_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&characterSetResults=utf8mb4
    username: root
    password: 0yUKxpK9nkAPRg4
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
  redis:
    host: 212.80.213.8
    port: 6379
    password: gaEvE9ben98OXmv
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 Minute
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: natsukashiiz.dev@gmail.com
    password: zavn qpoh qpot ocmq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
shop:
  jwt:
    pvKey: classpath:app.key
    pubKey: classpath:app.pub
    expiration:
      access: 1h
      refresh: 1d
  web:
    url:
      base: https://shop.natsukashiiz.online
      verification: https://shop.natsukashiiz.online/verification?code={CODE}
      resetPassword: https://shop.natsukashiiz.online/reset-password?email={EMAIL}&code={CODE}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.natsukashiiz.shop: DEBUG
